demo/urls.py
from django.contrib import admin
from django.urls import path,include,re_path
from demo_register.views import index
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',index,name='index'),
    path('register/', include('demo_register.urls')),

]+ static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

demo_register/urls.py
from django.urls import path,include,re_path

from . import views

app_name = 'demo_register'

urlpatterns = [
    path('',views.RegisterView.as_view(),name='register'),
    path('image/',views.RegisterView.as_view(),name='image'),
    path('image_demo/',views.image_demo,name='image_demo'),
    path('modify/',views.modifyView.as_view(),name='modify'),
    path('del_demo/',views.del_demo,name='del_demo'),
]

demo_register/models.py
from django.db import models


class UserProfile(models.Model):
    username = models.CharField(max_length=100)
    password = models.CharField(max_length=100)
    birthday = models.DateField()
    mobile = models.CharField(max_length=11,null=True,blank=True)
    width = models.FloatField()
    height = models.IntegerField()
    image = models.ImageField(upload_to='image/%Y/%m',default='image/default.png',max_length=100)

    class Meta:
        verbose_name = '用户信息'
        verbose_name_plural = verbose_name


class Image(models.Model):
    image = models.ImageField(upload_to='image/', default='image/default.png', max_length=100)

demo_register/forms.py
from django import forms
from .models import UserProfile,Image


class RegisterForm(forms.ModelForm):

    class Meta:
        model = UserProfile
        fields = ['username', 'password', 'birthday','mobile','width','height','image']


class ImageForm(forms.ModelForm):
    class Meta:
        model = Image
        fields = ['image']

demo_register/views.py
from django.shortcuts import render
from .forms import RegisterForm,ImageForm
from .models import UserProfile
from django.http import HttpResponse
from django.views.generic import View
from django.shortcuts import redirect,reverse
from .models import Image
from django.views.decorators.http import require_POST,require_GET
from django.core.paginator import Paginator


@require_GET
def index(request):
    all_user = UserProfile.objects.all()

    sort = request.GET.get('sort', '')

    if sort:
        if sort == 'birthday':
            all_user = UserProfile.objects.all().order_by('-birthday')
        elif sort == 'height':
            all_user = UserProfile.objects.all().order_by('-height')

    paginator = Paginator(all_user, 5)  # 每页分5
    page = request.GET.get('page')  # 获取浏览器页数请求参数
    page_demo = paginator.get_page(page)  # 获取分页数据对象
    current_page = page_demo.number  # 获取当前页码
    num_pages = paginator.num_pages  # 获取总页数

    around_count = 2  # 当前页前后2页

    left_has_more = False
    right_has_more = False

    if current_page <= around_count + 2:
        left_pages = range(1, current_page)
    else:
        left_has_more = True
        left_pages = range(current_page - around_count, current_page)

    if current_page >= num_pages - around_count - 1:
        right_pages = range(current_page + 1, num_pages + 1)
    else:
        right_has_more = True
        right_pages = range(current_page + 1, current_page + around_count + 1)

    return render(request,'index.html',locals())


class RegisterView(View):
    def get(self,request):
        return render(request,'regist.html')

    def post(self,request):
        register_form = RegisterForm(request.POST,request.FILES)
        if register_form.is_valid():
            register_form.save()
            return redirect(reverse('index'))
        else:
            return HttpResponse('注册失败，请检查格式！！！')


def image_demo(request):
    image_form = ImageForm(request.POST,request.FILES)
    if image_form.is_valid():
        image_form.save()


class modifyView(View):
    def get(self, request):
        return render(request,'modify.html')

    def post(self,request):
        register_form = RegisterForm(request.POST,request.FILES)
        if register_form.is_valid():
            register_form.save()
            return redirect(reverse('index'))
        else:
            return HttpResponse('注册失败，请检查格式！！！')


@require_POST
def del_demo(request):
    user_id = request.POST.get('del')
    print(user_id)
    user = UserProfile.objects.get(id=user_id)
    user.delete()
    return render(request,'index.html')

templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load staticfiles %}

    <meta charset="UTF-8">
    <title>index</title>
    <link href="{% static 'css/main.css' %}" type="text/css" rel="stylesheet"/>
    <script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>
</head>
<body>
<div id="main">
    <p>显示界面<span>(考核点 ②：数据库信息查询[无条件全查询])</span></p>
    {#    <form id="filter" method="get" action="" onclick="return false">#}
    {#        <ul>#}
    {#            <li><input type="button" id="Birthday" class="byChoose" name="byBirthday" value="生 日" /></li>#}
    {#            <li><input type="button" id="byHeight" class="byChoose" name="byHeight" value="身 高" /></li>#}
    {#            <li><a href="{% url 'index' %}?sort=birthday"></a></li>#}
    {#            <li><a href="{% url 'index' %}?sort=height"></a></li>#}
    {#            <li>附加考核点 ②：实现排序功能；同一个按钮第一次点击顺序排序，第二次点击时逆序排序</li>#}
    {#        </ul>#}
    {#    </form>#}
    <p>附加考核点 ②：实现排序功能；同一个按钮第一次点击顺序排序，第二次点击时逆序排序</p>
    <a href="{% url 'index' %}?sort=birthday">生日</a>
    <a href="{% url 'index' %}?sort=height">身高</a>

    <div class="showUser">
        <ul class="infoHead">
            <li>姓名</li>
            <li>生日</li>
            <li>手机</li>
            <li>身高</li>
            <li>操作</li>
        </ul>
        <!-- 示例显示区域 -->
        {% for demo in page_demo.object_list %}
            <ul class="showTips">
                <li>{{ demo.username }}</li>
                <li>{{ demo.birthday }}</li>
                <li>{{ demo.mobile }}</li>
                <li>{{ demo.height }}</li>
                <li><a href="{% url 'demo_register:modify' %}"><input type="button" id="modifytip" class="modify"
                                                                      name="modifytip" value="修 改"/></a></li>
                <li><input type="button" id='del-btn' class="delete" value="删除" data-id="{{ demo.id }}"/></li>
            </ul>
        {% endfor %}

        <!-- 以下部分为实际显示区域
        <ul class="informations">
            <li></li><li></li><li></li><li></li>
            <li><input type="button" id="modify1" class="modify" name="modify2" value="修 改" /></li>
            <li><input type="button" id="delete1" class="delete" name="delete1" value="删 除" /></li>
        </ul>
        -->
    </div>


    <span class="tips3">"考核点 ③：数据修改点击修改按钮会进入 modify "</span>
    <span class="tips4">"考核点 ④：数据删除点击删除按钮会删除该条数据记录，同时刷新 index，重新显示"</span>
    <span class="tips5">"附加考核点 ③：分页显示，页面最多显示5条数据记录，分页显示，实现页面前进后退跳转等功能"</span>


</div>

<div>
    <div class="">
        {% if page_demo.has_previous %}
            <a href="{% url 'index' %}?page={{ page_demo.previous_page_number }}">上一页</a>
        {% else %}
            <a href="javascript:void(0);">上一页</a>
        {% endif %}

        {% if left_has_more %}
            <a href="{% url 'index' %}?page=1">1</a>
            <a href="javascript:void(0);">...</a>
        {% endif %}

        {# 左边页码 #}

        {% for left_page in left_pages %}
            <a href="{% url 'index' %}?page={{ left_page }}">{{ left_page }}</a>
        {% endfor %}

        {# 当前页面 #}

        <a href="{% url 'index' %}?page={{ current_page }}"
           class="active">{{ current_page }}</a>

        {# 右边的页码 #}

        {% for right_page in right_pages %}
            <a href="{% url 'index' %}?page={{ right_page }}">{{ right_page }}</a>
        {% endfor %}

        {% if right_has_more %}
            <a href="javascript:void(0);">...</a>
            <a href="{% url 'index' %}?page={{ num_pages }}">{{ num_pages }}</a>
        {% endif %}

        {% if page_demo.has_next %}
            <a href="{% url 'index' %}?page={{ page_demo.next_page_number }}">下一页</a>
        {% else %}
            <a href="javascript:void(0);">下一页</a>
        {% endif %}
    </div>
</div>

</body>

<script>
    $(function () {
        var deleteBtns = $('#del-btn');
        deleteBtns.click(function () {
            var btn = $(this);
            var del = btn.attr('data-id');
            console.log(del);
            $.ajax({
                type: 'post',
                url: '{% url "demo_register:del_demo" %}',
                data: {
                    'del': del,
                },
                success: function () {
                    alert('删除成功');
                    window.location.reload();
                },
            });
        });
    });
</script>

{#<script>#}
{#    $(function () {#}
{#        $('#Birthday').click(function () {#}
{#            var del = $("input[name='del']").val();#}
{#            console.log(del);#}
{#            $.ajax({#}
{#                type:'post',#}
{#                url:'{% url "demo_register:del_demo" %}',#}
{#                data:{#}
{#                    'del':del,#}
{#                },#}
{#                success:function () {#}
{#                        alert('删除成功');#}
{#                        window.location.reload();#}
{#                },#}
{#            });#}
{##}
{#        });#}
{#    });#}
{#</script>#}


</html>

templates/modify.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>修改</title>
    <link href="css/main.css" type="text/css" rel="stylesheet" />
    <script src="js/jquery-3.2.1.min.js" type="text/javascript"></script>
    <script src="js/main.js" type="text/javascript"></script>
</head>
<body>
<div id="main">
    <form id="reg" method="post" action="{% url 'demo_register:modify' %}" enctype="multipart/form-data">
    <p>修改界面<span>(考核点 ③：数据库信息修改)</span><br /><span class="spetip">特殊说明：进入该页面，下表单中，须存在有欲修改用户的信息</span></p>
        <p>姓 名<input type="text" id="regusername" name="username" value="" /><span>dataType: varchar</span></p>
            <p>密 码<input type="text" id="regpassword" name="password" value="" /><span>dataType: varchar</span></p>
            <p>生 日<input type="date" name="birthday"><span>dataType: datetime</span></p>
            <p>电 话<input type="text" id="regphone" name="mobile" value="" /><span>dataType: char(11)</span></p>
            <p>体 重<input type="text" id="regweight" name="width" value="" /><span>dataType: double</span></p>
            <p>身 高<input type="text" id="regheight" name="height" value="" /><span>dataType: int</span></p>
            <p>头像<input type="file" id="image-btn" name="image" value=" " /><span>dataType: blob</span></p>
        <p><input type="submit" id="modsub" name="modsub" value="修 改"><span>"修改完成后，跳转至 index "</span></p>

</form>
</div>
</body>

{#<script>#}
{#    $(function () {#}
{#        $('#modsub').click(function () {#}
{#            var username = $('input[name="username"]').val();#}
{#            var password = $('input[name="password"]').val();#}
{#            var birthday = $('input[name="birthday"]').val();#}
{#            var mobile = $('input[name="mobile"]').val();#}
{#            var width = $('input[name="width"]').val();#}
{#            var height = $('input[name="height"]').val();#}
{#            var image = $('input[name="image"]').file[0];#}
{##}
{#            $.ajax({#}
{#                type:'post',#}
{#                url:'/demo_register/modify/',#}
{#                data:{#}
{#                    'username':username,#}
{#                    'password':password,#}
{#                    'birthday':birthday,#}
{#                    'phone':mobile,#}
{#                    'width':width,#}
{#                    'height':height,#}
{#                    'image':image#}
{#                },#}
{##}
{#                success:function (data) {#}
{#                    if (data.status == 'success') {#}
{#                        alert('注册成功');#}
{#                    }else {#}
{#                        alert('注册失败,请检查输入');#}
{#                    }#}
{#                },#}
{#            });#}
{##}
{#        });#}
{#    });#}
{##}
{#</script>#}

</html>

templates/regist.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load staticfiles %}
    <meta charset="UTF-8">
    <title>注册</title>
    <link href="{% static 'css/main.css' %}" type="text/css" rel="stylesheet" />
    <script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>
</head>
<body>
    <div id="main">
        <p>注册界面<span>(考核点 ①：数据库信息添加)</span></p>
        <form id="reg" method="post" action="{% url 'demo_register:register' %}" enctype="multipart/form-data">
            <p>姓 名<input type="text" id="regusername" name="username" value="" /><span>dataType: varchar</span></p>
            <p>密 码<input type="text" id="regpassword" name="password" value="" /><span>dataType: varchar</span></p>
            <p>生 日<input type="date" name="birthday"><span>dataType: datetime</span></p>
            <p>电 话<input type="text" id="regphone" name="mobile" value="" /><span>dataType: char(11)</span></p>
            <p>体 重<input type="text" id="regweight" name="width" value="" /><span>dataType: double</span></p>
            <p>身 高<input type="text" id="regheight" name="height" value="" /><span>dataType: int</span></p>
            <div>
                <img src="" class="image1" alt="">
            </div>
            <p>头像<input type="file" id="image-btn" name="image" value=" " /><span>dataType: blob</span></p>
            <p><input type="submit" id="regsub" name="regsub" value="提 交"><span>"点击提交，完成数据添加，跳转至 index "</span></p>
            {% csrf_token %}
        </form>
        <span class="tips">附加考核点 ①：同步处理<br />点击选择文件，完成头像上传<br />即同步显示在预留头像框内</span>
    </div>
</body>
{##}
{#<script>#}
{##}
{#    $('input[type="file"]').on('change',doUpload);#}
{#    function doUpload() {#}
{#        var image = this.file[0];#}
{#        $.ajax({#}
{#            type: 'post',#}
{#            url:'/demo_register/image_demo/',#}
{#            data: {#}
{#                'image':image#}
{#            },#}
{#            success:function () {#}
{#                alert('success');#}
{#            }#}
{#        })#}
{#    }#}


{#    $(function () {#}
{#        $('#regsub').click(function () {#}
{#            var username = $('input[name="username"]').val();#}
{#            var password = $('input[name="password"]').val();#}
{#            var birthday = $('input[name="birthday"]').val();#}
{#            var mobile = $('input[name="mobile"]').val();#}
{#            var width = $('input[name="width"]').val();#}
{#            var height = $('input[name="height"]').val();#}
{#            var image = $('input[name="image"]').file[0];#}
{##}
{#            $.ajax({#}
{#                type:'post',#}
{#                url:'/demo_register/register/',#}
{#                data:{#}
{#                    'username':username,#}
{#                    'password':password,#}
{#                    'birthday':birthday,#}
{#                    'phone':mobile,#}
{#                    'width':width,#}
{#                    'height':height,#}
{#                    'image':image#}
{#                },#}
{#                success:function (data) {#}
{#                    if (data.status == 'success') {#}
{#                        alert('注册成功');#}
{#                    }else {#}
{#                        alert('注册失败,请检查输入');#}
{#                    }#}
{#                },#}
{#            });#}
{##}
{#        });#}
{#    });#}
{##}
{##}
{#</script>#}

</html>